test: httpCoreClient
Byndyusoft/nest-http-client pull request #35
Opened 2022-09-27 19:41 UTC by Fun795

2022-10-01 06:34 UTC, KillWolfVlad requested changes
- [ ] Add tests for `HttpClient`
- [ ] Use `it.each` for more readability
- [ ] ~~Add tests for headers merge issue (moved to outer issue https://github.com/Byndyusoft/nest-http-client/issues/44)~~

2022-10-01 06:34 UTC, KillWolfVlad commented on package.json
> +    "rxjs": "^7.5.6",
Please, remove it from dependencies

2022-10-01 06:34 UTC, KillWolfVlad commented on src/__tests__/httpCoreClient.spec.ts
> +const axiosMock = axios as jest.Mocked<typeof axios>;
Mock axios like this:

```typescript
import { AxiosInstance } from "axios";
import { mock, MockProxy } from "jest-mock-extended";

import { HttpCoreClient } from "../httpCoreClient";

describe("httpCoreClient", () => {
  let axios: MockProxy<AxiosInstance>;

  let httpCoreClient: HttpCoreClient;

  beforeAll(() => {
    axios = mock();

    httpCoreClient = new HttpCoreClient({
      axios,
      config: {
        baseURL: "localhost",
      },
    });
  });
```

2022-10-04 09:49 UTC, Fun795 commented on package.json
> +    "rxjs": "^7.5.6",
moved to devDependencies

2023-02-18 12:47 UTC, KillWolfVlad requested changes

2023-02-18 12:47 UTC, KillWolfVlad commented on package.json
> +    "jest-mock-extended": "^3.0.1",
Move to dev deps

2023-02-18 13:27 UTC, KillWolfVlad commented
Closed in favor of #46

2023-02-18 13:27 UTC, closed without merging