[ISSUE-33] - client module injection docs
Byndyusoft/nest-http-client pull request #36
Opened 2022-10-07 09:33 UTC by codesprut

2022-10-07 09:55 UTC, lalumiere17 approved these changes

2022-10-08 05:26 UTC, KillWolfVlad requested changes

2022-10-08 05:26 UTC, KillWolfVlad commented on README.md
> +import axios from "axios";
Can you sort imports?

2022-10-08 05:26 UTC, KillWolfVlad commented on README.md
> +<summary>2. Inject client module into the application (appModule.ts)</summary>
Maybe instead `inject` we should use `import`?

2022-10-08 05:26 UTC, KillWolfVlad commented on README.md
> +<summary>2. Inject client module into the application (appModule.ts)</summary>
> `appModule.ts`

I think file name is not required here

2022-10-09 04:23 UTC, KillWolfVlad approved these changes

2022-10-10 09:42 UTC, lalumiere17 approved these changes

2022-10-15 04:08 UTC, merged